package apiSharpServer;

public enum ActionEnum {

    CONNECTED(1),
    REGISTER(10), LOGIN(11),
    SEND_MESSAGE(20), GET_LAST_MESSAGES(21),
    GET_LAST_CHATS(30), GET_CHAT_INFO(31), CREATE_CHAT(32), ADD_TO_CHAT(33),
    GET_INVITES(40),ACCEPT_INVITE(41),DENY_INVITE(42),


    SUCCEED(100),
    SUCCEED_LOGIN(110), SUCCEED_REGISTER(111),
    SUCCEED_MESSAGE_SEND(120), SUCCEED_GET_LAST_MESSAGES(121),
    SUCCEED_GET_LAST_CHATS(130), SUCCEED_GET_CHAT_INFO(131), SUCCEED_CREATE_CHAT(132), SUCCEED_ADD_TO_CHAT(133),
    SUCCEED_GET_INVITES(140),SUCCEED_ACCEPT_INVITE(141),SUCCEED_DENY_INVITE(142),

    ERROR(200),
    ERROR_LOGIN(210), ERROR_REGISTER(211),
    ERROR_MESSAGE_SEND(220), ERROR_GET_LAST_MESSAGES(221),
    ERROR_GET_LAST_CHATS(230), ERROR_GET_CHAT_INFO(231), ERROR_CREATE_CHAT(232), ERROR_ADD_TO_CHAT(233),
    ERROR_GET_INVITES(240), ERROR_ACCEPT_INVITE(241), ERROR_DENY_INVITE(242);
    private int in;
    ActionEnum(int i) {
        in = i;
    }
    public int getI(){
        return in;
    }
}
